---
spring:
  data:
  profiles: default
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/bootstrap
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
vaadin4spring:
  i18n:
    message-format-cache:
      enabled: false
    message-provider-cache:
      cleanup-interval-seconds: 5
logging:
  level:
    org.springframework: INFO



